DROP TABLE IF EXISTS TBL_BOOKS;
 
CREATE TABLE TBL_BOOKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  BOOK_NAME VARCHAR(250) NOT NULL,
  BOOK_AUTHOR VARCHAR(250) NOT NULL,
  BOOK_PUBLISHER VARCHAR(250) DEFAULT NULL
);